### PR TITLE
corrected reversal of active / passive convention for MultiplyQuatVec

### PR DESCRIPTION
**Pull request by wlenthe**
Updates #465

### CODE REVIEW

**Comment by imikejackson** [comment]
This is still wrong. Rotating a point [100] 120 Deg. about the [111] axis will result in the following:

*ACTIVE*
[010]

*PASSIVE*
[001]

these codes do NOT produce these results and in fact produce the opposite. The DREAM.3D version is correct. A Unit test has been added to verify these result.

**Comment by wlenthe** [comment]
As its stands MultiplyQuatVec does not match qu2om + MatrixMath::Multiply3x3with3x1. For example:
````c++
QuatF q = QuaternionMathF::New(0.5f, 0.5f, 0.5f, 0.5f);
std::vector<float> qVec(4, 0.5f), gVec(9, 0);
OrientationTransforms<std::vector<float>, float>::qu2om(qVec, gVec);

float g[3][3];
for(size_t i = 0; i < 3; i++) {
  for(size_t j = 0; j < 3; j++) {
    g[i][j] = gVec[3 * i + j];
  }
}

float vq[3], vg[3];
float v[3] = {1.0f, 0.0f, 0.0f};
QuaternionMathF::MultiplyQuatVec(q, v, vq, Rotations::Constants::epsijk);
MatrixMath::Multiply3x3with3x1(g, v, vg);
````
results in `vq = {0, 0, 1}` and `vg = {0, 1, 0}`. If qu2om outputs column major matrices it should be modified to avoid confusion with MatrixMath.

**Comment by sdonegan** [comment]
All orientation matrices within the transformation code should be following row major ordering.  It appears that qu2om does correctly follow this convention: when I step through the resulting orientation matrix in the debugger, I get row major ordering.  This can also be confirmed by looking at the way we copy values into a "g matrix" representation in the toGMatrix() function in OrientationArray.hpp, which is heavily used in many places throughout the code.

I have also verified that I can reproduce the results you've posted: the currently implemented MultiplyQuatVec function gives a passive transformation, while the Multiply3x3with3x1 gives an active transformation.  Since I am pretty confident that the orientation matrix has the correct ordering, I think the issue is more likely in Multiply3x3with3x1.  Should we be pre-multiplying for passive rotations?  We'll get some clarification on that, but it does appear that when you post-multiply you get the correct passive transformation (confirmed both manually, i.e. on paper, and by using Eigen).

Thanks for the heads up!

**Comment by imikejackson** [comment]
After digging deeper into the code and discussing with MDG@cmu the issue is that the initial quaternion of (0.5, 0.5, 0.5, 0.5) is a left handed quaternion where the Multiply3x3with3x1() function is expecting a rotation matrix derived from a right-handed quaternion. The right handed quaternion is the conjugate of the quaternion (0.5, 0.5, 0.5, 0.5). We have verified both the unit tests for the MultiplyQuatVec() and Multiply3x3with3x1() functions both give correct results. Refer to the "Rotations Tutorial Paper" equation 22 which defines the quaternion in terms of rotation angle and axis vector. Since DREAM.3D uses P=+1 your input quaternion should be ( <-0.5, -0.5, -0.5>, 0.5).

In the future we may add or rename the MultiplyQuatVec() function to add the "P" value as a parameter. 

Currently is it up to the programmer to be diligent in setting up all the representations correctly. DREAM.3D uses passive representation for all rotations.

**Comment by imikejackson** [comment]
Closing this pull request due to inability to obtain a CLA. The pull request may be reopened if a CLA is obtained in the future.

**Pull request closed without merging**
