### PR TITLE
Feature/473 metric based gb distributions

### PR DESCRIPTION
**Pull request by kglowins**

### CODE REVIEW

**Comment by sdonegan** [comment]
Thanks for implementing the metric based GBCD filter, Krzysztof!  Before we can begin the process of reviewing the code for merging, there is one additional matter.  BlueQuartz now has the policy that all external contributors need to sign our contributor license agreement (CLA), which can be found here:

http://dream3d.bluequartz.net/?page_id=448

Instructions on getting the signed agreement to us can be found in the agreement itself.  It is important to note that this agreement does not affect copyright in anyway, and that **you maintain the copyright and intellectual property to any code you contribute**.  All the agreement does is allow BlueQuartz the ability to license your code (under the BSD license) so that we can distribute it to the community.  CLAs are quite common in professionally maintained open source projects, and only serve to ensure that we have the flexibility to distribute the code as necessary and prove code provenance.  

If you have any questions about the CLA, please email secretary@bluequartz.net.

thanks,

-Sean

**Comment by kglowins** [comment]
Sean, I have just emailed signed CLA to the secretary.
-Krzysztof

**Comment by sdonegan** [comment]
Thanks, Krzysztof! A few minor cleanup points before merge in the pull request:

+ In the header file, please place your constants declarations (NUM_RESOL_CHOICES, DEFAULT_RESOL_CHOICE, etc.) in a namespace to avoid any name clashing.
+ In the SourceList.cmake file, move the filter (FindGBCD_MetricBased) up into alphabetical order. This helps sort things in the generated user manual.
+ DREAM.3D tries to avoid using underscores in filter and class names. Could you rename the filter class to "FindGBCDMetricBased" instead?

Also, we like to format our code in DREAM.3D a particular way, mostly regarding spaces. Eventually, we'll have an automatic program that can format the code for you, so for now it's not a big deal. The main thing we use is 2 spaces for any line indents and force tabs to be used as spaces. If you are in Visual Studio, you can enforce these settings by going to the Tools > Options > Text Editor > C/C++ menu as shown here:

capture

Setting the tab size and indent size to 2 and insert spaces checked gets the settings needed. Then you can go to the Edit > Advanced > Format Document menu to format the files with these settings. No worries if you can't get it done for this pull request, but good to know for the future.

Once those issues are addressed I'll take a second look at everything and we'll get it merged in.

thanks,

-Sean

**Comment by kglowins** [comment]
Sean- I've included your suggestions, as well as a couple of fixes and improvements. I believe that the code is now tested and ready for review. -Krzysztof

**Comment by sdonegan** [comment]
Sorry this took a while to get back to, we were waiting on pull requests because we were preparing for a release.

I've had the opportunity to take a closer look at the code and check the output, everything looks pretty solid.  A few last things to address:

1. At line 455 of the source: The initializer list in the constructor is out of order. The correct order should be:
  + m_CrystalStructures(NULL),
  + m_FeatureEulerAngles(NULL),
  + m_FeaturePhases(NULL),
  + m_SurfaceMeshFaceAreas(NULL),
  + m_SurfaceMeshFaceLabels(NULL),
  + m_SurfaceMeshFaceNormals(NULL),
  + m_SurfaceMeshFeatureFaceLabels(NULL),
  + m_NodeTypes(NULL)
2. At line 1176 of the source: There are more % formatters than arguments. Just need to cut the % formatters down to the first three.
3. At line 549 of the source: When creating the parameter requirement, the third argument should be DREAM3D:AttributeMatrixType::FaceFeature (instead of DREAM3D::AttributeMatrixType::Face).

Otherwise looks solid; I was able to successfully run the filter on the small IN100 and view the GBCD using GMT; everything looks correct.  Usually, we require new filters to be implemented with a unit test, but for complex filters like this, we'll design a pipeline around it to run each night as a check.  To help our checking, it would be good if you could let us know about what maximum MRD we should expect when running on the small IN100 data set, just to make sure everything is right on our end.

Once the few minor points are addressed above, I'll merge in this filter.  Thanks Krzysztof!

**Comment by kglowins** [comment]
Thank you for the review! I've corrected those parts of the code.

Of course, I can indicate some reference values, but we need to clearly define what input should I use. Do you have some standard (already cleaned-up) data set for testing? My point is that results will vary depending on alignment, cropping, meshing, smoothing, etc.

**Pull request merged**
