### PR TITLE
Corrected triangle winding bug in quick surface mesh (faces between a…

### PR DESCRIPTION
**Pull request by wlenthe**
… pair of grains now have a consistent normal after generation)

### CODE REVIEW

**Comment by wlenthe** [comment]
Example change on reconstruction of the IN100 dataset before (right) triangle winding is inconsistent across a boundary resulting in occasional flipped normals and face labels. After the correction (left) winding and face labels are uniform:
surface_normals
face_labels

**Comment by sdonegan** [comment]
Could I get some clarification on the original problem and the approach for the solution?  Is the problem that for a given grain, not all of its associated triangles had their normals pointing the correct direction, or is it something else?  Just want to understand exactly what is being addressed here before merging it in.

**Comment by wlenthe** [comment]
In its current form the quick mesh filter produces triangles wound such that the normals all point in the positive x/y/z direction (based on which type of voxel face they are created from) and faces are labeled [feature of lower index voxel, feature of higher index voxel]. This means if you looks at a single boundary (in the sense of what would be identified by the shared feature face filter, i.e. all the triangles bounded by feature 1 and 2) the normal may be flipped between 2 adjacent triangles which can be very problematic for some filters. Similarly the face labels will be swapped (some of the triangles may be labels [1, 2] while others are labeled [2, 1]). To correct this I changed the convention so that faces are labeled [samaller feature id, larger feature id] and triangles are wound such that the normals point from the face_label[0] to face_label[1].

**Comment by mgroeber** [comment]
Just to clarify though, the labeling was correct (ie normal pointed towards first feature of [I,j]), but there was no consistency for all triangles on a given boundary to point toward the same grain, correct?  If so, I am not sure what filters would have had a problem, since filters should be written working to the convention of the normal pointing to the first feature in the list.  With that said, I have no issue with there being an additional convention of always point towards one feature for a given boundary, since it shouldn't affect any filters and does make visualization 'prettier' in some sense.

**Comment by wlenthe** [comment]
In the existing implementation the normals are correct for all internal boundaries (there is an issue with external boundaries that I corrected with commit 8b4c5af), but as Mike stated there is no consistency for triangles pointing towards the same grain. I don't know if this affects any filters currently in the release but I've had issues with it in the past. It is also problematic when exporting the mesh to other applications.

**Comment by sdonegan** [comment]
One final clarification: this change still correctly has all triangle normals pointing towards the first Feature Id in the face labels array, correct?  I.e., for a give face lable (i, j), the triangle normal points towards i.  That is generally the assumed convention in DREAM.3D.  As long as that remains the case, then this can get merged in as it does seem to make the visualizations much better and would fix any potential inconsistencies along boundaries.

**Comment by wlenthe** [comment]
All normals point to the the first feature in the face labels (I had accidentally switched the outer triangle case but it is correct now)

**Comment by imikejackson** [comment]
Closing this pull request due to inability to obtain a CLA. The pull request may be reopened if a CLA is obtained in the future.

**Comment by eugenianietov** [comment]
Hi everyone,

I am working with a 3D volume of a sample and I am creating a surface mesh with Dream3D. The problem is that I am still getting abnormal triangle winding within grain boundaries as shown in the images below. However, the FaceLabels are consistent within the faces (they don't change within the same face). Any idea of what might be wrong?

test_FaceLabels_Y_W
test_Normals_Y_W

I also provide my pipeline in case you want to take a look. Thanks a lot in advance!!

[2-Ti_SurfaceMesh.json.zip](https://github.com/BlueQuartzSoftware/DREAM3D/files/9069922/2-Ti_SurfaceMesh.json.zip)

Eugenia

**Pull request closed without merging**
